### ISSUE TITLE
Error in page_rank

### ISSUE THREAD

**Issue by KevinMenden** [shmohammadi86/ACTIONet_legacy#1]
Hi,

I just tried to run ACTIONet, but got an error which I don't know how to interpret. I did a very basic testing run using only the most basic steps. 

`sce.object <- CreateSeuratObject(counts = ven, project = "VEN", min.cells = 3, min.features = 500)

sce.object <- import.sce.from.Seurat(sce.object)

sce.reduced <- reduce.sce(sce.object)

action <- run.ACTIONet(sce.reduced)`

The error message I receive is the following:
`
Error in page_rank(sub.ACTIONet, personalized = sub.cn, damping = alpha_val) : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value
`

I geht this message after the "Identify anchor cells" step (or during it).

Help would be appreciated!

On another mark, it would be very helpful if the functions in the R package had some kind of documentation. 

Best,
Kevin

**Comment by shmohammadi86** [comment]
Hi Kevin,

I did add an exception handler to deal with cases where your subnetworks are empty (which is most likely your case). Please update/reinstall ACTIONet, try again, and let me know how it goes.

**Comment by KevinMenden** [comment]
Yep - that solved it!

Thanks, that was impressively fast.
