### ISSUE TITLE
R help on functions is missing, github tutorial links are broken (not found) ...

### ISSUE THREAD

**Issue by therealgenna** [shmohammadi86/ACTIONet_legacy#4]
Hi Shahin,

There are no help pages for the package functions (?run.ACTIONet and others don't work).

Also, most of the tutorial links on the github main page aren't working (not found).

Is there an alternative to see how to use your package?

Thank you.

**Comment by shmohammadi86** [comment]
I've written a set of new tutorials for it that I would be releasing soon.
